// Writes docs/cli.md from the command definitions, so the reference cannot drift from the CLI.
//   bun run docs:cli

import { writeFile } from "node:fs/promises";
import path from "node:path";

import { GLOBAL_OPTIONS, type Command } from "../src/cli/command";
import { COMMANDS } from "../src/cli/main";

const INTRO = `# Command line

<!-- Generated by scripts/generate-cli-docs.ts from the command definitions. Do not edit by hand; run \`bun run docs:cli\`. -->

\`conveyor <command> [options]\`. Every command takes the global options, \`--help\` prints a command's
options, and \`--json\` prints machine-readable output where a command has any. Nothing reads a
plaintext credential from a command argument: passwords come from a prompt without echo, a file, or
stdin (\`-\`).

The home is \`--home\`, else \`CONVEYOR_HOME\`, else \`~/.conveyor\`; the \`service\` commands, \`upgrade\` and
\`rollback\` default to the home recorded in the installed systemd unit, so they also work under
\`sudo\`. The configuration is \`--config\`, else \`<home>/config/conveyor.yaml\`.

## Exit codes

| Code | Meaning |
| ---: | --- |
| 0 | Success |
| 1 | The command ran and failed (an operation error, a failed check, a timeout) |
| 2 | The command line is invalid |
| 3 | The configuration does not load or validate |
| 4 | The running service cannot be reached (it is stopped, or there is no control socket) |
| 5 | The service refused the request because a precondition does not hold (the reason is printed) |
`;

/** Prose for Markdown: placeholders such as <home> would otherwise be read as HTML tags. */
const prose = (text: string) => text.replace(/</g, "&lt;").replace(/\|/g, "\\|");
/** A table row: pipes are escaped, even inside code. */
const row = (name: string, spec: { value?: string; description: string }) =>
  `| \`--${name}${spec.value ? ` ${spec.value.replace(/\|/g, "\\|")}` : ""}\` | ${prose(spec.description)} |`;

function options(command: Command): string[] {
  const rows = Object.entries({ ...command.options }).map(([name, spec]) => row(name, spec));
  return rows.length === 0 ? [] : ["", "| Option | Description |", "| --- | --- |", ...rows];
}

export function renderCliDocs(commands: readonly Command[] = COMMANDS): string {
  const sections = commands.filter((command) => !command.hidden).map((command) => [
    `### \`conveyor ${command.name}${command.usage ? ` ${command.usage}` : ""}\``,
    "",
    prose(`${command.summary[0]!.toUpperCase()}${command.summary.slice(1)}.`),
    ...(command.details ? ["", prose(command.details.replace(/\n/g, " "))] : []),
    ...options(command),
  ].join("\n"));
  const globals = Object.entries(GLOBAL_OPTIONS).map(([name, spec]) => row(name, spec));
  return `${INTRO}\n## Global options\n\n| Option | Description |\n| --- | --- |\n${globals.join("\n")}\n\n## Commands\n\n${sections.join("\n\n")}\n`;
}

if (import.meta.main) {
  await writeFile(path.resolve(import.meta.dir, "../docs/cli.md"), renderCliDocs());
}
