import { writeFile } from "node:fs/promises";
import path from "node:path";

import { createTaskRegistry } from "../src/tasks/catalogue";
import type { TaskDefinition, TaskRegistry } from "../src/tasks/contract";

const INTRO = `# Tasks

<!-- Generated by scripts/generate-task-docs.ts from the task registry. Do not edit by hand; run \`bun run docs:tasks\`. -->

A stage is a chain of tasks. Every stage has two lists: \`actions\` (do the stage's job) and a non-empty \`exit-gate\` (prove the job is done). Conditions the next stage needs belong to the previous exit gate; there are no entrance gates.

## Kinds

- **load**: the sole writer of one provider snapshot (\`item\`, \`workspace\`, \`change\`, \`ci\`). Safe to re-run. Loads are implicit and never appear in stage lists.
- **check**: a pure function of the context it declares in \`reads\`. It performs no I/O and writes nothing. Only checks appear in an \`exit-gate\`.
- **act**: reconciles external state toward a desired result: observe first, then do only the missing work. It declares the snapshots it \`invalidates\` and is safe to resume after a crash. Only acts appear in \`actions\`.
- **tool**: callable only through an agent's MCP grant. Never listed in a stage.

## Results

A task returns one of:

- \`pass\`: the task is done.
- \`pending\`: not yet (for example CI is still running, or an agent asked a question). The engine parks the item and resumes after \`wait.pollMs\` or an early webhook. A pending action keeps the cursor on that task; a pending exit gate is re-evaluated as a whole with fresh loads, and actions are not repeated.
- \`fail\`: a domain failure, routed by \`onFail\`.

A thrown error is an infrastructure error, not a domain failure; it uses the bounded infrastructure retry policy.

## Task entries

\`\`\`yaml
actions:
  - { id: startCi, task: ci.start, when: ci.enabled }
exit-gate:
  - id: ciGate
    task: ci.passed
    when: ci.required
    wait: { timeout: unlimited, poll: 5m }
    onFail: { return: implementation }
\`\`\`

- **Instance id**: \`id\` defaults to the task name when that name occurs once in the list. A task name used more than once needs an explicit \`id\`. Ids are unique within a stage. Repository overrides, execution records, script results and idempotency keys address the instance id, never an array index.
- **Implicit loads**: a task receives only the context keys it declares in \`reads\`. Before it runs, the engine runs the load task for every snapshot key it reads that is not loaded yet or was invalidated by an earlier act. The exit gate starts with everything unloaded. \`conveyor check-config\` shows these loads as \`(load <key>)\` lines.
- **Dataflow checks**: reading a snapshot key needs a registered load task. Reading \`agent\` or \`script\` needs an earlier act in the same stage's \`actions\` that writes it. \`script.succeeded\` must name a \`script.run\` instance of the same stage in \`with.run\`.
- **Guards**: \`when\` is one of \`ci.enabled\` (mode is not disabled), \`ci.required\` or \`ci.advisory\`, evaluated from the repository's \`ci.mode\` at compile time. A task whose guard is false is left out of the plan. The exit gate must still be non-empty.
- **with**: the task's configuration, validated against its schema when the config loads. \`script.run\` requires \`with.recovery\`.
- **wait**: \`{ timeout, poll }\`. Each field comes from the entry, else the task's own default, else \`settings.taskDefaults.wait\`. \`timeout: unlimited\` never times out.
- **onFail**: \`retry\`, \`{ return: <stage> }\` (another stage of the pipeline) or \`{ stop: <state> }\` (a \`labels.states\` key). An exit-gate failure defaults to \`retry\`, bounded by the stage's \`retries\`; an action failure defaults to \`stop: blocked\`. \`settings.maxReturns\` bounds loops across stages.

## Exit-gate semantics

Gate open: advance. Gate \`fail\`: run the stage's actions again with \`run.feedback\`, unless \`onFail\` routes elsewhere. Gate \`pending\`: park, then re-evaluate the whole gate with fresh loads.

## Repository overrides

\`repositories.<id>.overrides.stages.<stage>.<actions|exit-gate>.<instance id>\` replaces \`with\`, merges \`wait\` and replaces \`onFail\`. Naming a stage, list or instance that does not exist is a configuration error.

`;

function cell(text: string): string {
  return text.replace(/\|/g, "\\|").replace(/\s*\n\s*/g, " ").trim();
}

function effects(def: TaskDefinition<any, any, any>): string {
  const parts: string[] = [];
  if (def.writes.length > 0) parts.push(`writes ${def.writes.join(", ")}`);
  if (def.invalidates.length > 0) parts.push(`invalidates ${def.invalidates.join(", ")}`);
  return parts.length > 0 ? parts.join("; ") : "-";
}

export function renderTaskDocs(registry: TaskRegistry): string {
  const groups = new Map<string, TaskDefinition<any, any, any>[]>();
  for (const def of [...registry.list()].sort((a, b) => a.name.localeCompare(b.name))) {
    const group = def.name.slice(0, def.name.indexOf("."));
    groups.set(group, [...(groups.get(group) ?? []), def]);
  }
  const sections = [INTRO + "## Task catalogue\n"];
  if (groups.size === 0) sections.push("No tasks are registered yet.\n");
  for (const [group, defs] of groups) {
    const rows = defs.map(
      (def) =>
        `| \`${def.name}\` | ${def.kind} | ${def.reads.length > 0 ? def.reads.join(", ") : "-"} | ${effects(def)} | ${cell(def.description)} |`,
    );
    sections.push(
      [`### ${group}`, "", "| Task | Kind | Reads | Writes / invalidates | Description |", "| --- | --- | --- | --- | --- |", ...rows, ""].join("\n"),
    );
  }
  return sections.join("\n");
}

if (import.meta.main) {
  const target = path.join(import.meta.dir, "../docs/tasks.md");
  await writeFile(target, renderTaskDocs(createTaskRegistry()));
  console.log(`Wrote ${target}`);
}
